apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab
spec:
  selector:
    matchLabels:
      app: collab
  template:
    metadata:
      labels:
        app: collab
    spec:
      containers:
        - name: collab
          image: distractedcat/collab:3.0.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: :4000
            - name: REDIS_URI
              value: redis:6379
            - name: USER_SERVICE_URI
              value: http://user-service:3001
          ports:
            - containerPort: 4000
              name: collab