apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: modembcc/matching-service:6.0.0
          imagePullPolicy: Always
          env:
            - name: RABBIT_URI
              value: amqp://grp14:grp14@rabbitmq/
            - name: REDIS_URI
              value: redis:6379
            - name: BACKEND_MATCH_URI
              value: http://backend:9090/match
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
