apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep
spec:
  selector:
    matchLabels:
      app: peerprep
  template:
    metadata:
      labels:
        app: peerprep
    spec:
      containers:
        - name: peerprep
          image: modembcc/peerprep:7.0.2
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_QUESTION_SERVICE
              value: backend
            - name: NEXT_PUBLIC_USER_SERVICE
              value: users
            - name: NEXT_PUBLIC_MATCHING_SERVICE
              value: matchmaking
            - name: NEXT_PUBLIC_STORAGE_BLOB
              value: blob
            - name: NEXT_PUBLIC_NGINX
              value: http://nginx:70
            - name: NEXT_PUBLIC_COLLAB
              value: collab
            - name: DEV_ENV
              value: not
            - name: NEXT_PUBLIC_FORMATTER
              value: formatter
          ports:
            - containerPort: 3000
              name: peerprep
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
