apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storage-blob-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-blob-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
