import TitleBar from "@/components/shared/TitleBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Container from "@/components/shared/Container";
import styles from "@/style/layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PeerPrep",
  description: "Generated by create next app",
  icons: {
    icon: "icon.ico",
    // Icon taken from https://www.flaticon.com/free-icon/code_1157109
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TitleBar />
        <Container className={styles.main_container}>{children}</Container>
      </body>
    </html>
  );
}
